export const nftProperties = {
  fields: [
    { name: "name", type: "text", label: "NAME", maxlength: 255, value: "" },
    {
      name: "description",
      type: "text",
      label: "DESCRIPTION",
      maxlength: 255,
      value: "",
    },
    {
      name: "externalLink",
      type: "text",
      label: "EXTERNAL LINK",
      maxlength: 255,
      value: "",
    },
    {
      name: "image",
      type: "file",
      label: "IMAGE",
      maxlength: 255,
      value: undefined,
      accept: ".jpg,.jpeg,.png,.gif,.avif,.jfif",
    },
    {
      name: "youtubeUrl",
      type: "text",
      label: "YOUTUBE URL",
      maxlength: 255,
      value: "",
    },
    {
      name: "animationUrl",
      type: "text",
      label: "ANIMATION_URL",
      maxlength: 255,
      value: "",
    },
    {
      name: "ownerName",
      type: "text",
      label: "OWNER NAME",
      maxlength: 255,
      value: "",
    },
    {
      name: "doingBusinessAs",
      type: "text",
      label: "DOING BUSINESS AS",
      maxlength: 15,
      value: "",
    },
    {
      name: "propertyId",
      type: "text",
      label: "PROPERTY ID",
      maxlength: 15,
      value: "",
      readOnly: true,
    },
    { name: "geoId", type: "text", label: "GEO ID", maxlength: 255, value: "" },
    {
      name: "legalDescription",
      type: "text",
      label: "LEGAL DESCRIPTION",
      maxlength: 255,
      value: "",
    },
    {
      name: "stateCode",
      type: "text",
      label: "STATE CODE",
      maxlength: 255,
      value: "",
    },
    // {name: "address", type: "text", label: "ADDRESS", maxlength: 255, value: ''},
    {
      name: "taxJurisdictions",
      type: "text",
      label: "TAX JURISDICTIONS",
      maxlength: 255,
      value: "",
    },
    {
      name: "appraisedValue",
      type: "text",
      label: "APPRAISED VALUE",
      maxlength: 50,
      value: "",
    },
    {
      name: "neighborhood",
      type: "text",
      label: "NEIGHBORHOOD",
      maxlength: 255,
      value: "",
    },
    {
      name: "abstractCode",
      type: "text",
      label: "ABSTRACT CODE",
      maxlength: 15,
      value: "",
    },
    {
      name: "ccrDeclaration",
      type: "text",
      label: "CCR DECLARATION",
      maxlength: 50,
      value: "",
    },
    {
      name: "operatingAgreement",
      type: "text",
      label: "OPERATING AGRMT.",
      placeholder: "OPERATING AGREEMENT",
      maxlength: 50,
      value: "",
    },
    {
      name: "membershipContract",
      type: "text",
      label: "MEM. CONTRACT",
      placeholder: "MEMBERSHIP CONTRACT",
      maxlength: 50,
      value: "",
    },
    {
      name: "daoContract",
      type: "text",
      label: "DAO CONTRACT",
      maxlength: 50,
      value: "",
    },
    {
      name: "heating",
      type: "text",
      label: "HEATING",
      maxlength: 50,
      value: "",
    },
    {
      name: "cooling",
      type: "text",
      label: "COOLING",
      maxlength: 50,
      value: "",
    },
    {
      name: "_id",
      type: "text",
      label: "ID",
      maxlength: 50,
      value: "",
      hide: true,
    },
  ],
  attributes: [
    {
      trait_type: "market_value_of_home",
      type: "number",
      label: "Market Value of Home",
      value: "",
    },
    {
      trait_type: "square_feet",
      type: "number",
      label: "Square Feet",
      value: "",
    },
    {
      trait_type: "estimated_monthly_payment",
      type: "number",
      label: "Est. Monthly Payment",
      value: "",
    },
    { trait_type: "year_built", type: "date", label: "Year Built", value: "" },
    { trait_type: "lot_size", type: "number", label: "Lot Size", value: "" },
    {
      trait_type: "monthly_hoa_fee",
      type: "number",
      label: "Monthly HOA Fee",
      value: "",
    },
    {
      trait_type: "number_of_parking",
      type: "number",
      label: "Number of Parking",
      value: "",
    },
    {
      trait_type: "price_per_sqft",
      type: "number",
      label: "Price Per Sq. ft.",
      value: "",
    },
    {
      trait_type: "bed_bath_dimensions",
      type: "number",
      label: "Bed Bath Dimensions",
      value: "",
    },
    {
      trait_type: "time_on_marketplace",
      type: "number",
      label: "Time on Marketplace",
      value: "",
    },
    { trait_type: "views", type: "number", label: "Views", value: "" },
    { trait_type: "saves", type: "number", label: "Saves", value: "" },
  ],
  standout_features: [],
}
